// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApVHx4pLA1xa1XLUcQpELusZ5IqCJQil0',
    appId: '1:644404380872:web:6104703b657ff79e79d1fd',
    messagingSenderId: '644404380872',
    projectId: 'advance-dev2025',
    authDomain: 'advance-dev2025.firebaseapp.com',
    storageBucket: 'advance-dev2025.firebasestorage.app',
    measurementId: 'G-9SQ32NH0T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwVSSw8Umo15MhhstQg0F1PQlPMOyoSew',
    appId: '1:644404380872:android:5dd55f199fbca2c479d1fd',
    messagingSenderId: '644404380872',
    projectId: 'advance-dev2025',
    storageBucket: 'advance-dev2025.firebasestorage.app',
  );
}
